# -*- coding: utf-8 -*-
"""1.bioinformatics_intro.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17I-zaVsBqtE6MxeoU-gg2nylbcErVs33
"""

!pip install biopython
from Bio.Seq import Seq

dna= Seq("ACTACTG")
print(dna)
print(dna.complement())
print(dna.reverse_complement())

print